language: csharp
solution: Concordia.Framework.sln
mono:
  - latest
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore Concordia.Framework.sln
after_script:
  - nunit-console Concordia.Framework.Tests/bin/Release/Concordia.Framework.Tests.dll
