language: csharp
dist: trusty
solution: Nightingale.sln
mono: none
dotnet: 2.0.0

install:
- dotnet restore

script:
  - dotnet build
  - dotnet test Nightingale.Tests

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./nuget-deploy.sh && ./nuget-deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    branch: develop
